//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpmmm
{
    using System;
    using System.Collections.Generic;
    
    public partial class put
    {
        public int Id_put { get; set; }
        public string FIO { get; set; }
        public string Strana { get; set; }
        public string City { get; set; }
        public string Datta { get; set; }
        public string Price { get; set; }
    }
}
