//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpmmm
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id_user { get; set; }
        public string FIO { get; set; }
        public string Passport { get; set; }
        public string age { get; set; }
        public string birthday { get; set; }
    }
}
